name = "SPHKernels"
uuid = "54ab9b88-2582-4358-b400-8014666a1730"
authors = ["LudwigBoess <lboess@usm.lmu.de>"]
version = "2.4.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
LinearAlgebra = "1"
PrecompileTools = "1"
julia = "1.6"
